export interface WeaponItem {
    id: string;
    name: string;
    type: string;
    category: 'ar' | 'sniper' | 'smg' | 'heavy' | 'pistol' | 'mythic';
    rarity: 'mythic' | 'legendary' | 'epic' | 'rare';
    dmg: number;
    fireDelay: number;
    magSize: number;
    pellets: number;
    spread: number;
    range: number;
    cost: number;
    inrPrice: number;
    originalPrice: number;
    desc: string;
    badge: string;
}

export const WEAPONS_CATALOG: Record<string, WeaponItem> = {
    // ==========================================
    // 1. ASSAULT RIFLES (20+ Guns)
    // ==========================================
    ak47: {
        id: 'ak47',
        name: 'AK-47 Kalashnikov',
        type: 'Assault Rifle',
        category: 'ar',
        rarity: 'rare',
        dmg: 48,
        fireDelay: 110,
        magSize: 30,
        pellets: 1,
        spread: 0.012,
        range: 400,
        cost: 0,
        inrPrice: 0,
        originalPrice: 299,
        desc: 'Default 7.62mm heavy assault rifle with reliable stopping power.',
        badge: '💥 STARTER DEFAULT'
    },
    m416_glacier: {
        id: 'm416_glacier',
        name: 'M416 Glacier Max',
        type: 'Mythic AR',
        category: 'ar',
        rarity: 'mythic',
        dmg: 68,
        fireDelay: 85,
        magSize: 45,
        pellets: 1,
        spread: 0.003,
        range: 650,
        cost: 0,
        inrPrice: 199,
        originalPrice: 999,
        desc: 'Glacial cryo-infused 5.56mm carbine with ice trail muzzle flash and zero recoil kick.',
        badge: '❄️ GLACIER MYTHIC'
    },
    m4a1_tactical: {
        id: 'm4a1_tactical',
        name: 'M4A1 Tactical SpecOps',
        type: 'Carbine',
        category: 'ar',
        rarity: 'epic',
        dmg: 54,
        fireDelay: 92,
        magSize: 35,
        pellets: 1,
        spread: 0.005,
        range: 520,
        cost: 0,
        inrPrice: 49,
        originalPrice: 399,
        desc: 'High-precision 5.56mm assault carbine with red holographic optic sight.',
        badge: '🎯 PRECISION 5.56MM'
    },
    akm_fossil: {
        id: 'akm_fossil',
        name: 'AKM Desert Fossil',
        type: 'Assault Rifle',
        category: 'ar',
        rarity: 'legendary',
        dmg: 62,
        fireDelay: 105,
        magSize: 40,
        pellets: 1,
        spread: 0.009,
        range: 480,
        cost: 0,
        inrPrice: 99,
        originalPrice: 599,
        desc: 'Ancient fossil engraved 7.62mm beast capable of shredding enemy armor.',
        badge: '🦖 FOSSIL LEGENDARY'
    },
    scar_sandstorm: {
        id: 'scar_sandstorm',
        name: 'SCAR-L Sandstorm Gold',
        type: 'Assault Rifle',
        category: 'ar',
        rarity: 'legendary',
        dmg: 56,
        fireDelay: 90,
        magSize: 40,
        pellets: 1,
        spread: 0.004,
        range: 550,
        cost: 0,
        inrPrice: 79,
        originalPrice: 499,
        desc: 'Ultra-stable Belgian assault rifle with desert digital camouflage finish.',
        badge: '🏜️ SANDSTORM GOLD'
    },
    groza_blood: {
        id: 'groza_blood',
        name: 'Groza Blood Raven',
        type: 'Bullpup AR',
        category: 'ar',
        rarity: 'mythic',
        dmg: 74,
        fireDelay: 80,
        magSize: 40,
        pellets: 1,
        spread: 0.007,
        range: 500,
        cost: 0,
        inrPrice: 249,
        originalPrice: 1299,
        desc: 'Airdrop-exclusive 7.62mm bullpup monster with devastating close-range DPS.',
        badge: '🩸 BLOOD RAVEN'
    },
    m416_fool: {
        id: 'm416_fool',
        name: 'M416 The Fool Joker',
        type: 'Mythic AR',
        category: 'ar',
        rarity: 'mythic',
        dmg: 70,
        fireDelay: 84,
        magSize: 45,
        pellets: 1,
        spread: 0.003,
        range: 620,
        cost: 0,
        inrPrice: 299,
        originalPrice: 1499,
        desc: 'Joker themed animated dragon mouth weapon with hypnotic chromatic aura.',
        badge: '🃏 THE FOOL MYTHIC'
    },
    beryl_dragon: {
        id: 'beryl_dragon',
        name: 'Beryl M762 Dragon Slayer',
        type: 'Assault Rifle',
        category: 'ar',
        rarity: 'legendary',
        dmg: 65,
        fireDelay: 88,
        magSize: 40,
        pellets: 1,
        spread: 0.008,
        range: 510,
        cost: 0,
        inrPrice: 129,
        originalPrice: 699,
        desc: 'High rate-of-fire 7.62mm rifle with dragon scale carbon fiber handguard.',
        badge: '🐉 DRAGON BERYL'
    },
    aug_cyber: {
        id: 'aug_cyber',
        name: 'AUG A3 Cyberpunk 2077',
        type: 'Bullpup AR',
        category: 'ar',
        rarity: 'legendary',
        dmg: 58,
        fireDelay: 82,
        magSize: 42,
        pellets: 1,
        spread: 0.003,
        range: 600,
        cost: 0,
        inrPrice: 149,
        originalPrice: 799,
        desc: 'Neon cyan synthwave assault rifle with pinpoint precision barrel rifling.',
        badge: '⚡ CYBERPUNK 2077'
    },
    famas_valkyrie: {
        id: 'famas_valkyrie',
        name: 'FAMAS Valkyrie Burst',
        type: 'Burst / Auto AR',
        category: 'ar',
        rarity: 'epic',
        dmg: 52,
        fireDelay: 68,
        magSize: 35,
        pellets: 1,
        spread: 0.006,
        range: 480,
        cost: 0,
        inrPrice: 69,
        originalPrice: 399,
        desc: 'French military bullpup with blistering 1000 RPM cycle speed.',
        badge: '🦅 VALKYRIE BURST'
    },
    m16a4_aurora: {
        id: 'm16a4_aurora',
        name: 'M16A4 Aurora Borealis',
        type: 'Burst Rifle',
        category: 'ar',
        rarity: 'epic',
        dmg: 60,
        fireDelay: 75,
        magSize: 40,
        pellets: 1,
        spread: 0.004,
        range: 580,
        cost: 0,
        inrPrice: 59,
        originalPrice: 349,
        desc: 'Hyper-velocity 3-round burst rifle coated in shimmering northern lights.',
        badge: '🌌 AURORA BURST'
    },
    galil_ace: {
        id: 'galil_ace',
        name: 'Galil ACE-32 Urban Ops',
        type: 'Assault Rifle',
        category: 'ar',
        rarity: 'rare',
        dmg: 50,
        fireDelay: 100,
        magSize: 35,
        pellets: 1,
        spread: 0.008,
        range: 460,
        cost: 0,
        inrPrice: 39,
        originalPrice: 249,
        desc: 'Modernized tactical combat rifle built for harsh jungle conditions.',
        badge: '🏙️ URBAN OPS'
    },
    qbz_jade: {
        id: 'qbz_jade',
        name: 'QBZ-95 Imperial Jade',
        type: 'Bullpup AR',
        category: 'ar',
        rarity: 'legendary',
        dmg: 55,
        fireDelay: 90,
        magSize: 40,
        pellets: 1,
        spread: 0.005,
        range: 530,
        cost: 0,
        inrPrice: 89,
        originalPrice: 549,
        desc: 'Sanhok rainforest specialist rifle inlaid with pure emerald jade.',
        badge: '💎 IMPERIAL JADE'
    },
    g36c_frost: {
        id: 'g36c_frost',
        name: 'G36C Arctic Frostbite',
        type: 'Compact AR',
        category: 'ar',
        rarity: 'epic',
        dmg: 53,
        fireDelay: 89,
        magSize: 35,
        pellets: 1,
        spread: 0.005,
        range: 510,
        cost: 0,
        inrPrice: 49,
        originalPrice: 299,
        desc: 'Sub-zero polymer composite assault rifle with frozen snowflake tracer rounds.',
        badge: '❄️ ARCTIC FROST'
    },
    honey_badger: {
        id: 'honey_badger',
        name: 'Honey Badger Spec-Ops .300',
        type: 'Integrally Suppressed AR',
        category: 'ar',
        rarity: 'legendary',
        dmg: 59,
        fireDelay: 86,
        magSize: 35,
        pellets: 1,
        spread: 0.006,
        range: 470,
        cost: 0,
        inrPrice: 119,
        originalPrice: 649,
        desc: 'Whisper-quiet .300 Blackout caliber weapon with built-in silencer.',
        badge: '🦡 SILENT BADGER'
    },
    ace31_inferno: {
        id: 'ace31_inferno',
        name: 'ACE31 Hellfire Inferno',
        type: 'Assault Rifle',
        category: 'ar',
        rarity: 'mythic',
        dmg: 72,
        fireDelay: 82,
        magSize: 45,
        pellets: 1,
        spread: 0.004,
        range: 540,
        cost: 0,
        inrPrice: 219,
        originalPrice: 1099,
        desc: 'Volcanic forged barrel emitting molten magma sparks with each trigger pull.',
        badge: '🔥 HELLFIRE MYTHIC'
    },
    tar21_future: {
        id: 'tar21_future',
        name: 'TAR-21 Future Soldier',
        type: 'Bullpup AR',
        category: 'ar',
        rarity: 'rare',
        dmg: 51,
        fireDelay: 94,
        magSize: 30,
        pellets: 1,
        spread: 0.007,
        range: 490,
        cost: 0,
        inrPrice: 29,
        originalPrice: 199,
        desc: 'Lightweight Israeli combat platform with ergonomic thumbhole grip.',
        badge: '🛡️ FUTURE SOLDIER'
    },
    an94_hyperburst: {
        id: 'an94_hyperburst',
        name: 'AN-94 Abakan 2-Tap',
        type: 'Assault Rifle',
        category: 'ar',
        rarity: 'legendary',
        dmg: 66,
        fireDelay: 95,
        magSize: 35,
        pellets: 1,
        spread: 0.002,
        range: 590,
        cost: 0,
        inrPrice: 139,
        originalPrice: 749,
        desc: 'Fires two bullets in instantaneous 1800 RPM hyperburst through one single hole.',
        badge: '⚡ 2-TAP HYPERBURST'
    },
    fal_paratrooper: {
        id: 'fal_paratrooper',
        name: 'FN FAL Paratrooper 7.62',
        type: 'Heavy Battle Rifle',
        category: 'ar',
        rarity: 'epic',
        dmg: 64,
        fireDelay: 120,
        magSize: 30,
        pellets: 1,
        spread: 0.006,
        range: 610,
        cost: 0,
        inrPrice: 79,
        originalPrice: 449,
        desc: 'The right arm of the free world chambered in full-power 7.62x51mm NATO.',
        badge: '🪂 PARATROOPER'
    },
    m416_golden_lion: {
        id: 'm416_golden_lion',
        name: 'M416 Golden Lion Emperor',
        type: 'Mythic AR',
        category: 'ar',
        rarity: 'mythic',
        dmg: 71,
        fireDelay: 83,
        magSize: 45,
        pellets: 1,
        spread: 0.003,
        range: 640,
        cost: 0,
        inrPrice: 279,
        originalPrice: 1399,
        desc: '24K gold plated chassis with diamond crown sights and royal lion engravings.',
        badge: '🦁 GOLDEN EMPEROR'
    },

    // ==========================================
    // 2. SNIPERS & DMRs (20+ Guns)
    // ==========================================
    awm_godzilla: {
        id: 'awm_godzilla',
        name: 'AWM Godzilla Roar .300',
        type: 'Heavy Bolt Sniper',
        category: 'sniper',
        rarity: 'mythic',
        dmg: 280,
        fireDelay: 1050,
        magSize: 10,
        pellets: 1,
        spread: 0.0001,
        range: 1000,
        cost: 0,
        inrPrice: 299,
        originalPrice: 1599,
        desc: 'The undisputed King of Snipers. 1-Shot eliminates any helmet or heavy body armor.',
        badge: '🦖 GODZILLA ROAR'
    },
    awp_sniper: {
        id: 'awp_sniper',
        name: 'AWP Heavy Arctic Magnum',
        type: 'Sniper Rifle',
        category: 'sniper',
        rarity: 'legendary',
        dmg: 210,
        fireDelay: 1100,
        magSize: 10,
        pellets: 1,
        spread: 0.0003,
        range: 950,
        cost: 0,
        inrPrice: 99,
        originalPrice: 599,
        desc: 'Iconic high-impact sniper rifle with 8x telescopic optic zoom.',
        badge: '💀 1-SHOT LETHAL'
    },
    kar98k_dragon: {
        id: 'kar98k_dragon',
        name: 'Kar98k Dragon Slayer',
        type: 'Vintage Bolt Sniper',
        category: 'sniper',
        rarity: 'legendary',
        dmg: 175,
        fireDelay: 980,
        magSize: 5,
        pellets: 1,
        spread: 0.0004,
        range: 850,
        cost: 0,
        inrPrice: 89,
        originalPrice: 499,
        desc: 'Classic Mauser bolt action sniper adorned with gold dragon engravings.',
        badge: '🐉 DRAGON SLAYER'
    },
    m24_pharaoh: {
        id: 'm24_pharaoh',
        name: 'M24 Pharaoh Golden Tomb',
        type: 'Bolt-Action Sniper',
        category: 'sniper',
        rarity: 'mythic',
        dmg: 195,
        fireDelay: 920,
        magSize: 10,
        pellets: 1,
        spread: 0.0002,
        range: 920,
        cost: 0,
        inrPrice: 249,
        originalPrice: 1299,
        desc: 'Ancient Egyptian sarcophagus aesthetic with cursed sand smoke effects.',
        badge: '👑 PHARAOH MYTHIC'
    },
    barrett_50cal: {
        id: 'barrett_50cal',
        name: 'Barrett M82 .50 BMG Anti-Material',
        type: 'Anti-Material Sniper',
        category: 'sniper',
        rarity: 'mythic',
        dmg: 320,
        fireDelay: 1200,
        magSize: 10,
        pellets: 1,
        spread: 0.0001,
        range: 1200,
        cost: 0,
        inrPrice: 349,
        originalPrice: 1799,
        desc: 'Fires massive 12.7mm .50 BMG rounds that blast through tanks and barricades.',
        badge: '💥 .50 BMG TITAN'
    },
    mk14_explosive: {
        id: 'mk14_explosive',
        name: 'MK14 EBR Auto DMR',
        type: 'Full-Auto DMR',
        category: 'sniper',
        rarity: 'legendary',
        dmg: 95,
        fireDelay: 130,
        magSize: 20,
        pellets: 1,
        spread: 0.004,
        range: 750,
        cost: 0,
        inrPrice: 149,
        originalPrice: 799,
        desc: 'Full-auto 7.62mm marksman rifle with extreme armor-piercing kinetic energy.',
        badge: '⚡ FULL AUTO DMR'
    },
    slr_phantom: {
        id: 'slr_phantom',
        name: 'SLR Phantom Spectre',
        type: 'Designated Marksman',
        category: 'sniper',
        rarity: 'epic',
        dmg: 88,
        fireDelay: 180,
        magSize: 20,
        pellets: 1,
        spread: 0.003,
        range: 700,
        cost: 0,
        inrPrice: 69,
        originalPrice: 399,
        desc: 'Heavy 7.62mm semi-automatic DMR with high muzzle velocity and clean sight picture.',
        badge: '👻 PHANTOM DMR'
    },
    sks_cyberpunk: {
        id: 'sks_cyberpunk',
        name: 'SKS Cyberpunk Neon Pulse',
        type: 'Semi-Auto DMR',
        category: 'sniper',
        rarity: 'epic',
        dmg: 80,
        fireDelay: 160,
        magSize: 25,
        pellets: 1,
        spread: 0.004,
        range: 650,
        cost: 0,
        inrPrice: 59,
        originalPrice: 349,
        desc: 'Custom tactical stock with neon purple illuminated ammo round counters.',
        badge: '💜 CYBER SKS'
    },
    vss_assassin: {
        id: 'vss_assassin',
        name: 'VSS Vintorez Silent Assassin',
        type: 'Subsonic Sniper',
        category: 'sniper',
        rarity: 'rare',
        dmg: 58,
        fireDelay: 95,
        magSize: 30,
        pellets: 1,
        spread: 0.005,
        range: 450,
        cost: 0,
        inrPrice: 39,
        originalPrice: 249,
        desc: 'Fully suppressed 9x39mm automatic marksman rifle that produces 0 radar sound.',
        badge: '🤫 100% SILENT'
    },
    mosin_nagant: {
        id: 'mosin_nagant',
        name: 'Mosin-Nagant White Death',
        type: 'Bolt-Action Sniper',
        category: 'sniper',
        rarity: 'epic',
        dmg: 170,
        fireDelay: 950,
        magSize: 5,
        pellets: 1,
        spread: 0.0004,
        range: 820,
        cost: 0,
        inrPrice: 69,
        originalPrice: 399,
        desc: 'Historic Finnish winter warfare sniper rifle wrapped in burlap snow camouflage.',
        badge: '❄️ WHITE DEATH'
    },
    cheytac_m200: {
        id: 'cheytac_m200',
        name: 'CheyTac M200 Intervention',
        type: 'Extreme Range Sniper',
        category: 'sniper',
        rarity: 'mythic',
        dmg: 290,
        fireDelay: 1150,
        magSize: 7,
        pellets: 1,
        spread: 0.0001,
        range: 1300,
        cost: 0,
        inrPrice: 319,
        originalPrice: 1699,
        desc: 'The famous quickscope intervention chambered in .408 CheyTac sub-MOA rounds.',
        badge: '🎯 360 QUICKSCOPE'
    },
    dsr50_stealth: {
        id: 'dsr50_stealth',
        name: 'DSR-50 Black Stealth Bullpup',
        type: 'Heavy Bullpup Sniper',
        category: 'sniper',
        rarity: 'legendary',
        dmg: 230,
        fireDelay: 1080,
        magSize: 8,
        pellets: 1,
        spread: 0.0002,
        range: 980,
        cost: 0,
        inrPrice: 169,
        originalPrice: 899,
        desc: 'German precision engineered bullpup chassis with spare magazine holder.',
        badge: '🕶️ BLACK STEALTH'
    },
    svd_dragunov: {
        id: 'svd_dragunov',
        name: 'SVD Dragunov Red Star',
        type: 'Designated Marksman',
        category: 'sniper',
        rarity: 'rare',
        dmg: 82,
        fireDelay: 200,
        magSize: 15,
        pellets: 1,
        spread: 0.003,
        range: 720,
        cost: 0,
        inrPrice: 39,
        originalPrice: 249,
        desc: 'Soviet semi-automatic marksman rifle with PSO-1 illuminated rangefinder reticle.',
        badge: '⭐ RED STAR'
    },
    mini14_frost: {
        id: 'mini14_frost',
        name: 'Mini-14 Glacier Speed DMR',
        type: 'Light DMR',
        category: 'sniper',
        rarity: 'epic',
        dmg: 65,
        fireDelay: 110,
        magSize: 30,
        pellets: 1,
        spread: 0.002,
        range: 680,
        cost: 0,
        inrPrice: 59,
        originalPrice: 349,
        desc: 'Near-zero bullet drop 5.56mm rapid DMR with high tap-fire capability.',
        badge: '⚡ SPEED DMR'
    },
    l115a3_gold: {
        id: 'l115a3_gold',
        name: 'L115A3 Royal British Magnum',
        type: 'Sniper Rifle',
        category: 'sniper',
        rarity: 'legendary',
        dmg: 225,
        fireDelay: 1060,
        magSize: 8,
        pellets: 1,
        spread: 0.0002,
        range: 960,
        cost: 0,
        inrPrice: 159,
        originalPrice: 849,
        desc: 'Holds the verified record for longest distance tactical confirmed sniper hit.',
        badge: '🇬🇧 ROYAL MAGNUM'
    },

    // ==========================================
    // 3. SMGs & FAST-FIRE (20+ Guns)
    // ==========================================
    vector_cyberpunk: {
        id: 'vector_cyberpunk',
        name: 'Vector Super-V Cyberpunk',
        type: 'Ultra Rapid SMG',
        category: 'smg',
        rarity: 'mythic',
        dmg: 44,
        fireDelay: 48,
        magSize: 45,
        pellets: 1,
        spread: 0.012,
        range: 320,
        cost: 0,
        inrPrice: 189,
        originalPrice: 949,
        desc: '1200 RPM Super-V recoil mitigation system that empties a full mag in 1.5 seconds.',
        badge: '⚡ 1200 RPM VECTOR'
    },
    mp5_frostbite: {
        id: 'mp5_frostbite',
        name: 'MP5K Frostbite Special',
        type: 'SMG',
        category: 'smg',
        rarity: 'epic',
        dmg: 38,
        fireDelay: 65,
        magSize: 40,
        pellets: 1,
        spread: 0.014,
        range: 350,
        cost: 0,
        inrPrice: 49,
        originalPrice: 299,
        desc: 'German 9mm submachine gun with cryogenic blue muzzle flash.',
        badge: '❄️ FROSTBITE SMG'
    },
    p90_viper: {
        id: 'p90_viper',
        name: 'P90 Viper Venom 50-Round',
        type: 'Personal Defense Weapon',
        category: 'smg',
        rarity: 'legendary',
        dmg: 42,
        fireDelay: 58,
        magSize: 50,
        pellets: 1,
        spread: 0.010,
        range: 400,
        cost: 0,
        inrPrice: 119,
        originalPrice: 649,
        desc: 'Bullpup 5.7x28mm weapon with top-mounted 50-round horizontal magazine.',
        badge: '🐍 50-ROUND VIPER'
    },
    uzi_neon: {
        id: 'uzi_neon',
        name: 'Micro UZI Neon Flash',
        type: 'Micro SMG',
        category: 'smg',
        rarity: 'epic',
        dmg: 34,
        fireDelay: 50,
        magSize: 35,
        pellets: 1,
        spread: 0.020,
        range: 280,
        cost: 0,
        inrPrice: 49,
        originalPrice: 299,
        desc: 'High cyclic rate close-quarters room clearer with hip-fire laser pointer.',
        badge: '⚡ NEON FLASH'
    },
    thompson_gold: {
        id: 'thompson_gold',
        name: 'Tommy Gun 1928 Gangster Gold',
        type: 'Drum SMG',
        category: 'smg',
        rarity: 'legendary',
        dmg: 46,
        fireDelay: 78,
        magSize: 50,
        pellets: 1,
        spread: 0.015,
        range: 360,
        cost: 0,
        inrPrice: 99,
        originalPrice: 599,
        desc: '.45 ACP Chicago Typewriter with 50-round drum mag and golden heat shield.',
        badge: '🎩 GANGSTER GOLD'
    },
    bizon_frost: {
        id: 'bizon_frost',
        name: 'PP-19 Bizon Helical Drum',
        type: 'Large Cap SMG',
        category: 'smg',
        rarity: 'rare',
        dmg: 36,
        fireDelay: 72,
        magSize: 53,
        pellets: 1,
        spread: 0.016,
        range: 340,
        cost: 0,
        inrPrice: 29,
        originalPrice: 199,
        desc: 'Russian submachine gun with under-barrel 53-round helical cylinder magazine.',
        badge: '🔋 53-ROUND HELIX'
    },
    mpx_shadow: {
        id: 'mpx_shadow',
        name: 'SIG MPX Shadow Operator',
        type: 'Tactical SMG',
        category: 'smg',
        rarity: 'legendary',
        dmg: 45,
        fireDelay: 62,
        magSize: 40,
        pellets: 1,
        spread: 0.008,
        range: 380,
        cost: 0,
        inrPrice: 129,
        originalPrice: 699,
        desc: 'Short-stroke gas piston system delivering AR-15 ergonomics in an SMG package.',
        badge: '🕶️ SHADOW OPERATOR'
    },
    ump45_arctic: {
        id: 'ump45_arctic',
        name: 'UMP45 Arctic SpecOps',
        type: 'Heavy SMG',
        category: 'smg',
        rarity: 'rare',
        dmg: 45,
        fireDelay: 95,
        magSize: 35,
        pellets: 1,
        spread: 0.009,
        range: 390,
        cost: 0,
        inrPrice: 29,
        originalPrice: 199,
        desc: 'Heavy hitting .45 ACP submachine gun with ultra-low horizontal recoil.',
        badge: '❄️ ARCTIC UMP'
    },
    mp7_specops: {
        id: 'mp7_specops',
        name: 'HK MP7A2 Armor Piercer',
        type: 'PDW',
        category: 'smg',
        rarity: 'legendary',
        dmg: 43,
        fireDelay: 55,
        magSize: 40,
        pellets: 1,
        spread: 0.009,
        range: 390,
        cost: 0,
        inrPrice: 139,
        originalPrice: 749,
        desc: '4.6x30mm high-penetration cartridges that slice straight through level 3 vest plates.',
        badge: '🛡️ ARMOR PIERCER'
    },
    mac10_blaze: {
        id: 'mac10_blaze',
        name: 'MAC-10 Hellfire Blaze',
        type: 'Micro Machine Pistol',
        category: 'smg',
        rarity: 'epic',
        dmg: 35,
        fireDelay: 45,
        magSize: 32,
        pellets: 1,
        spread: 0.024,
        range: 240,
        cost: 0,
        inrPrice: 59,
        originalPrice: 349,
        desc: '1300 RPM bullet hose with flaming muzzle sparks for instant point-blank meltdowns.',
        badge: '🔥 1300 RPM BLAZE'
    },
    scorpion_evo: {
        id: 'scorpion_evo',
        name: 'CZ Scorpion EVO 3 A1',
        type: 'Tactical SMG',
        category: 'smg',
        rarity: 'epic',
        dmg: 40,
        fireDelay: 60,
        magSize: 35,
        pellets: 1,
        spread: 0.011,
        range: 360,
        cost: 0,
        inrPrice: 69,
        originalPrice: 399,
        desc: 'Czech polymer submachine gun with folding stock and Picatinny quad rail.',
        badge: '🦂 SCORPION EVO'
    },
    ppsh41_drum: {
        id: 'ppsh41_drum',
        name: 'PPSh-41 Red Army 71-Drum',
        type: 'WW2 Heavy SMG',
        category: 'smg',
        rarity: 'legendary',
        dmg: 39,
        fireDelay: 56,
        magSize: 71,
        pellets: 1,
        spread: 0.018,
        range: 330,
        cost: 0,
        inrPrice: 119,
        originalPrice: 649,
        desc: 'Soviet 7.62x25mm Tokarev submachine gun with massive 71-round drum magazine.',
        badge: '🥁 71-ROUND DRUM'
    },

    // ==========================================
    // 4. SHOTGUNS & HEAVY LMGs (20+ Guns)
    // ==========================================
    dbs_double: {
        id: 'dbs_double',
        name: 'DBS Double-Barrel Death Pump',
        type: 'Bullpup Shotgun',
        category: 'heavy',
        rarity: 'mythic',
        dmg: 26,
        fireDelay: 280,
        magSize: 14,
        pellets: 14,
        spread: 0.055,
        range: 180,
        cost: 0,
        inrPrice: 199,
        originalPrice: 999,
        desc: 'Dual-tube bullpup shotgun firing two 14-pellet blasts in instant succession.',
        badge: '💥 28 PELLETS DBS'
    },
    s12k_armored: {
        id: 's12k_armored',
        name: 'Saiga-12 S12K Armored Doom',
        type: 'Semi-Auto Shotgun',
        category: 'heavy',
        rarity: 'legendary',
        dmg: 22,
        fireDelay: 220,
        magSize: 10,
        pellets: 9,
        spread: 0.060,
        range: 160,
        cost: 0,
        inrPrice: 99,
        originalPrice: 599,
        desc: 'AK-chassis semi-automatic 12-gauge shotgun that accepts rifle muzzle attachments.',
        badge: '💀 S12K DOOM'
    },
    dp28_dragon: {
        id: 'dp28_dragon',
        name: 'DP-28 Silver Dragon Disc',
        type: 'Heavy Machine Gun',
        category: 'heavy',
        rarity: 'legendary',
        dmg: 66,
        fireDelay: 110,
        magSize: 47,
        pellets: 1,
        spread: 0.007,
        range: 580,
        cost: 0,
        inrPrice: 129,
        originalPrice: 699,
        desc: 'The Dinner Plate LMG with bipod stabilization for zero recoil prone spraying.',
        badge: '🍽️ SILVER DRAGON'
    },
    m249_saw: {
        id: 'm249_saw',
        name: 'M249 SAW 150-Belt Heavy',
        type: 'Squad Automatic Weapon',
        category: 'heavy',
        rarity: 'mythic',
        dmg: 58,
        fireDelay: 75,
        magSize: 150,
        pellets: 1,
        spread: 0.009,
        range: 620,
        cost: 0,
        inrPrice: 249,
        originalPrice: 1299,
        desc: '150-round non-stop belt fed machine gun capable of blowing up entire squads and trucks.',
        badge: '⛓️ 150-ROUND SAW'
    },
    mg3_cyber: {
        id: 'mg3_cyber',
        name: 'MG3 Cyber Shredder 990',
        type: 'Airdrop Light MG',
        category: 'heavy',
        rarity: 'mythic',
        dmg: 62,
        fireDelay: 60,
        magSize: 75,
        pellets: 1,
        spread: 0.008,
        range: 650,
        cost: 0,
        inrPrice: 279,
        originalPrice: 1399,
        desc: 'German 7.62mm beast toggled to 990 RPM extreme cycle mode. Melts enemy armor.',
        badge: '⚡ 990 RPM MG3'
    },
    benelli_m4: {
        id: 'benelli_m4',
        name: 'Benelli M4 Super 90 Tactical',
        type: 'Auto Shotgun',
        category: 'heavy',
        rarity: 'epic',
        dmg: 24,
        fireDelay: 320,
        magSize: 8,
        pellets: 8,
        spread: 0.050,
        range: 200,
        cost: 0,
        inrPrice: 69,
        originalPrice: 399,
        desc: 'US Military standard semi-automatic combat shotgun with auto-regulating gas system.',
        badge: '🎯 BENELLI M4'
    },
    spas12_urban: {
        id: 'spas12_urban',
        name: 'SPAS-12 Urban Assault',
        type: 'Combat Shotgun',
        category: 'heavy',
        rarity: 'epic',
        dmg: 25,
        fireDelay: 420,
        magSize: 8,
        pellets: 8,
        spread: 0.055,
        range: 170,
        cost: 0,
        inrPrice: 59,
        originalPrice: 349,
        desc: 'Iconic Italian combat shotgun with top-folding stock and high stopping force.',
        badge: '💥 SPAS-12'
    },
    aa12_drum: {
        id: 'aa12_drum',
        name: 'AA-12 Full-Auto 20-Drum Shotgun',
        type: 'Full-Auto Shotgun',
        category: 'heavy',
        rarity: 'mythic',
        dmg: 20,
        fireDelay: 180,
        magSize: 20,
        pellets: 8,
        spread: 0.065,
        range: 190,
        cost: 0,
        inrPrice: 229,
        originalPrice: 1199,
        desc: 'Constant-recoil full-auto 12-gauge drum shotgun with zero kickback.',
        badge: '🥁 FULL AUTO AA12'
    },
    pkm_titan: {
        id: 'pkm_titan',
        name: 'PKM Titan 100-Box',
        type: 'General Purpose MG',
        category: 'heavy',
        rarity: 'legendary',
        dmg: 65,
        fireDelay: 92,
        magSize: 100,
        pellets: 1,
        spread: 0.009,
        range: 640,
        cost: 0,
        inrPrice: 149,
        originalPrice: 799,
        desc: '7.62x54mmR heavy cartridge machine gun with non-disintegrating metallic ammo belt.',
        badge: '🛡️ PKM TITAN'
    },
    remington_870: {
        id: 'remington_870',
        name: 'Remington 870 Express Hunter',
        type: 'Pump Shotgun',
        category: 'heavy',
        rarity: 'rare',
        dmg: 22,
        fireDelay: 650,
        magSize: 6,
        pellets: 8,
        spread: 0.060,
        range: 150,
        cost: 0,
        inrPrice: 19,
        originalPrice: 149,
        desc: 'Classic reliable steel-receiver pump action 12-gauge shotgun.',
        badge: '🌲 EXPRESS HUNTER'
    },
    minigun_vulcan: {
        id: 'minigun_vulcan',
        name: 'M134 Vulcan 6-Barrel Minigun',
        type: 'Rotary Machine Gun',
        category: 'heavy',
        rarity: 'mythic',
        dmg: 52,
        fireDelay: 35,
        magSize: 300,
        pellets: 1,
        spread: 0.018,
        range: 700,
        cost: 0,
        inrPrice: 399,
        originalPrice: 1999,
        desc: 'Electric rotary 6-barrel minigun firing 3000 rounds per minute with spinning barrel animations.',
        badge: '🌪️ 3000 RPM VULCAN'
    },

    // ==========================================
    // 5. PISTOLS & MELEE (15+ Guns)
    // ==========================================
    deagle_gold: {
        id: 'deagle_gold',
        name: 'Desert Eagle Golden Lion .50 AE',
        type: 'Heavy Hand Cannon',
        category: 'pistol',
        rarity: 'mythic',
        dmg: 110,
        fireDelay: 350,
        magSize: 7,
        pellets: 1,
        spread: 0.005,
        range: 350,
        cost: 0,
        inrPrice: 149,
        originalPrice: 799,
        desc: 'Pocket sniper pistol firing massive .50 Action Express rounds with golden shine.',
        badge: '🦁 .50 AE CANNON'
    },
    glock18_auto: {
        id: 'glock18_auto',
        name: 'Glock-18 Full-Auto 33-Mag',
        type: 'Machine Pistol',
        category: 'pistol',
        rarity: 'legendary',
        dmg: 36,
        fireDelay: 52,
        magSize: 33,
        pellets: 1,
        spread: 0.022,
        range: 220,
        cost: 0,
        inrPrice: 89,
        originalPrice: 499,
        desc: 'Selective fire full-auto polymer pistol with extended 33-round stick magazine.',
        badge: '⚡ FULL AUTO GLOCK'
    },
    python_magnum: {
        id: 'python_magnum',
        name: 'Colt Python .357 Royal Magnum',
        type: 'Revolver',
        category: 'pistol',
        rarity: 'epic',
        dmg: 92,
        fireDelay: 420,
        magSize: 6,
        pellets: 1,
        spread: 0.004,
        range: 340,
        cost: 0,
        inrPrice: 59,
        originalPrice: 349,
        desc: '6-inch polished stainless steel barrel with ventilated rib and walnut target grips.',
        badge: '🤠 .357 MAGNUM'
    },
    p18c_burst: {
        id: 'p18c_burst',
        name: 'P18C Cyber Stinger',
        type: 'Automatic Pistol',
        category: 'pistol',
        rarity: 'rare',
        dmg: 32,
        fireDelay: 60,
        magSize: 25,
        pellets: 1,
        spread: 0.018,
        range: 200,
        cost: 0,
        inrPrice: 29,
        originalPrice: 199,
        desc: 'Rapid secondary sidearm capable of finishing low-health foes in an instant.',
        badge: '🦂 CYBER STINGER'
    },
    r1895_cowboy: {
        id: 'r1895_cowboy',
        name: 'Nagant R1895 Gas-Seal Revolver',
        type: 'Heavy Revolver',
        category: 'pistol',
        rarity: 'rare',
        dmg: 78,
        fireDelay: 550,
        magSize: 7,
        pellets: 1,
        spread: 0.006,
        range: 300,
        cost: 0,
        inrPrice: 19,
        originalPrice: 149,
        desc: 'Unique 7-shot gas-seal cylinder revolver compatible with standard suppressors.',
        badge: '🎯 GAS-SEAL 7-SHOT'
    },
    laser_katana: {
        id: 'laser_katana',
        name: 'Cyber Laser Katana Blade',
        type: 'Melee Energy Blade',
        category: 'pistol',
        rarity: 'mythic',
        dmg: 250,
        fireDelay: 380,
        magSize: 999,
        pellets: 1,
        spread: 0.08,
        range: 40,
        cost: 0,
        inrPrice: 229,
        originalPrice: 1199,
        desc: 'High-frequency plasma edge katana blade that cuts through soldiers in a single slice.',
        badge: '⚔️ PLASMA KATANA'
    },

    // ==========================================
    // 6. MYTHIC GOD TIER & SPECIALS (12+ Guns)
    // ==========================================
    m416_imperial: {
        id: 'm416_imperial',
        name: 'M416 Imperial Red Dragon',
        type: 'God Tier Mythic',
        category: 'mythic',
        rarity: 'mythic',
        dmg: 78,
        fireDelay: 78,
        magSize: 50,
        pellets: 1,
        spread: 0.001,
        range: 750,
        cost: 0,
        inrPrice: 349,
        originalPrice: 1799,
        desc: 'Ancient draconic essence forged into 5.56mm alloy with continuous red lightning trails.',
        badge: '👑 GOD TIER DRAGON'
    },
    awm_void: {
        id: 'awm_void',
        name: 'AWM Void Walker Singularity',
        type: 'God Tier Sniper',
        category: 'mythic',
        rarity: 'mythic',
        dmg: 350,
        fireDelay: 1000,
        magSize: 12,
        pellets: 1,
        spread: 0.0001,
        range: 1500,
        cost: 0,
        inrPrice: 399,
        originalPrice: 1999,
        desc: 'Discharges micro black-hole dimensional vortexes. Instant kill anywhere on target.',
        badge: '🌌 VOID SINGULARITY'
    },
    akm_inferno: {
        id: 'akm_inferno',
        name: 'AKM Lord of Hellfire',
        type: 'God Tier Mythic',
        category: 'mythic',
        rarity: 'mythic',
        dmg: 84,
        fireDelay: 92,
        magSize: 45,
        pellets: 1,
        spread: 0.003,
        range: 650,
        cost: 0,
        inrPrice: 329,
        originalPrice: 1699,
        desc: 'Burning demonic skull frame with active lava rivers flowing across the receiver.',
        badge: '🔥 HELLFIRE LORD'
    },
    plasma_cannon: {
        id: 'plasma_cannon',
        name: 'Plasma Cannon X1 Overcharge',
        type: 'Energy Heavy Rifle',
        category: 'mythic',
        rarity: 'mythic',
        dmg: 120,
        fireDelay: 160,
        magSize: 30,
        pellets: 1,
        spread: 0.002,
        range: 800,
        cost: 0,
        inrPrice: 369,
        originalPrice: 1899,
        desc: 'Fires high-energy cyan plasma orbs that vaporize enemy waves and vehicles on contact.',
        badge: '⚡ PLASMA CANNON'
    },
    raygun_pulsar: {
        id: 'raygun_pulsar',
        name: 'Raygun Mark II Pulsar',
        type: 'Wonder Weapon',
        category: 'mythic',
        rarity: 'mythic',
        dmg: 140,
        fireDelay: 140,
        magSize: 30,
        pellets: 1,
        spread: 0.001,
        range: 900,
        cost: 0,
        inrPrice: 449,
        originalPrice: 2299,
        desc: 'Legendary sci-fi wonder weapon firing 3-round piercing green beam bursts.',
        badge: '🛸 WONDER WEAPON'
    },
    quantum_disintegrator: {
        id: 'quantum_disintegrator',
        name: 'Quantum Disintegrator Q-9',
        type: 'Experimental God Gun',
        category: 'mythic',
        rarity: 'mythic',
        dmg: 180,
        fireDelay: 180,
        magSize: 25,
        pellets: 1,
        spread: 0.0005,
        range: 1000,
        cost: 0,
        inrPrice: 499,
        originalPrice: 2499,
        desc: 'Unstable quantum antimatter emitter that dissolves enemy targets into subatomic particles.',
        badge: '⚛️ QUANTUM DISINTEGRATOR'
    }
};
