// WEAPONS CATALOG ES MODULE COMPATIBILITY LAYER
export const WEAPONS_CATALOG = {
    ak47: {
        id: 'ak47',
        name: 'AK-47 Kalashnikov',
        type: 'Assault Rifle',
        category: 'ar',
        rarity: 'rare',
        dmg: 48,
        fireDelay: 110,
        magSize: 30,
        pellets: 1,
        spread: 0.012,
        range: 400,
        cost: 0,
        inrPrice: 0,
        originalPrice: 299,
        desc: 'Default 7.62mm heavy assault rifle with reliable stopping power.',
        badge: '💥 STARTER DEFAULT'
    },
    m416_glacier: {
        id: 'm416_glacier',
        name: 'M416 Glacier Max',
        type: 'Mythic AR',
        category: 'ar',
        rarity: 'mythic',
        dmg: 68,
        fireDelay: 85,
        magSize: 45,
        pellets: 1,
        spread: 0.005,
        range: 550,
        cost: 380,
        inrPrice: 29,
        originalPrice: 799,
        desc: 'Legendary icy blue hit effect with ice shard muzzle velocity.',
        badge: '❄️ FAMOUS MYTHIC'
    },
    m416_fool: {
        id: 'm416_fool',
        name: 'M416 The Fool',
        type: 'Mythic AR',
        category: 'ar',
        rarity: 'mythic',
        dmg: 66,
        fireDelay: 88,
        magSize: 45,
        pellets: 1,
        spread: 0.006,
        range: 520,
        cost: 360,
        inrPrice: 25,
        originalPrice: 699,
        desc: 'Joker animated skin with purple muzzle flash and psychotic laughter kill broadcast.',
        badge: '🃏 MYTHIC CLASSIC'
    },
    awm: {
        id: 'awm',
        name: 'AWM .300 Magnum',
        type: 'Sniper Rifle',
        category: 'sniper',
        rarity: 'legendary',
        dmg: 185,
        fireDelay: 1200,
        magSize: 7,
        pellets: 1,
        spread: 0.001,
        range: 1200,
        cost: 450,
        inrPrice: 35,
        originalPrice: 899,
        desc: 'One shot, one kill high-caliber sniper rifle with extreme accuracy.',
        badge: '🎯 INSTANT ONE-SHOT'
    },
    awm_godzilla: {
        id: 'awm_godzilla',
        name: 'AWM Godzilla Radiant',
        type: 'Mythic Sniper',
        category: 'sniper',
        rarity: 'mythic',
        dmg: 240,
        fireDelay: 1100,
        magSize: 10,
        pellets: 1,
        spread: 0.0005,
        range: 1500,
        cost: 650,
        inrPrice: 49,
        originalPrice: 1299,
        desc: 'Atomic neon blue blast beam with titan level destruction.',
        badge: '🦖 GODZILLA TITAN'
    },
    barrett_m82: {
        id: 'barrett_m82',
        name: 'Barrett M82 .50 Cal',
        type: 'Anti-Materiel',
        category: 'sniper',
        rarity: 'legendary',
        dmg: 220,
        fireDelay: 1400,
        magSize: 10,
        pellets: 1,
        spread: 0.001,
        range: 1400,
        cost: 580,
        inrPrice: 42,
        originalPrice: 999,
        desc: 'Heavy 50mm anti-vehicle armor-piercing sniper rifle.',
        badge: '💣 ARMOR CRUSHER'
    },
    shotgun: {
        id: 'shotgun',
        name: 'S1897 Trench Shotgun',
        type: 'Pump Shotgun',
        category: 'shotgun',
        rarity: 'rare',
        dmg: 28,
        fireDelay: 750,
        magSize: 5,
        pellets: 9,
        spread: 0.055,
        range: 180,
        cost: 150,
        inrPrice: 9,
        originalPrice: 199,
        desc: 'Deadly 12-gauge close-quarters combat pump shotgun.',
        badge: '💥 CQC SHREDDER'
    },
    minigun: {
        id: 'minigun',
        name: 'M134 Vulcan Minigun',
        type: 'Heavy Machinegun',
        category: 'heavy',
        rarity: 'legendary',
        dmg: 54,
        fireDelay: 50,
        magSize: 200,
        pellets: 1,
        spread: 0.024,
        range: 650,
        cost: 750,
        inrPrice: 59,
        originalPrice: 1499,
        desc: 'Six-barrel rotary machinegun with 4,000 RPM suppressive rate of fire.',
        badge: '🌪️ 4000 RPM CHAOS'
    },
    plasma_rifle: {
        id: 'plasma_rifle',
        name: 'Plasma Arc Disruptor',
        type: 'Mythic Sci-Fi',
        category: 'mythic',
        rarity: 'mythic',
        dmg: 110,
        fireDelay: 100,
        magSize: 60,
        pellets: 1,
        spread: 0.002,
        range: 900,
        cost: 880,
        inrPrice: 69,
        originalPrice: 1999,
        desc: 'Superheated ionized plasma bolts that melt armored enemy hulls.',
        badge: '⚡ SCI-FI PLASMA'
    },
    deagle: {
        id: 'deagle',
        name: 'Desert Eagle .50 AE',
        type: 'Heavy Pistol',
        category: 'pistol',
        rarity: 'epic',
        dmg: 88,
        fireDelay: 320,
        magSize: 7,
        pellets: 1,
        spread: 0.008,
        range: 350,
        cost: 220,
        inrPrice: 15,
        originalPrice: 399,
        desc: 'Hand cannon with immense stopping power.',
        badge: '🦅 HAND CANNON'
    }
};
